### ISSUE TITLE
core dumps when scp'ing a file

### ISSUE THREAD

**Issue by lovelaced** [tmathmeyer/tint3#20]
Here's the debug output:

*** Error in `tint3': free(): invalid next size (fast): 0x0000000001097020 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x72055)[0x7f2f628e0055]
/usr/lib/libc.so.6(+0x779a6)[0x7f2f628e59a6]
/usr/lib/libc.so.6(+0x7818e)[0x7f2f628e618e]
tint3[0x405d42]
tint3[0x403b06]
tint3[0x403962]
tint3[0x403c27]
tint3[0x402b4f]
/usr/lib/libc.so.6(__libc_start_main+0xf0)[0x7f2f6288e610]
tint3[0x402869]
======= Memory map: ========
00400000-0040d000 r-xp 00000000 08:03 2643571                            /usr/bin/tint3
0060c000-0060d000 rw-p 0000c000 08:03 2643571                            /usr/bin/tint3
00f97000-010a1000 rw-p 00000000 00:00 0                                  [heap]
7f2f54000000-7f2f54021000 rw-p 00000000 00:00 0 
7f2f54021000-7f2f58000000 ---p 00000000 00:00 0 
7f2f5c000000-7f2f5c022000 rw-p 00000000 00:00 0 
7f2f5c022000-7f2f60000000 ---p 00000000 00:00 0 
7f2f603d9000-7f2f603ef000 r-xp 00000000 08:03 2619819                    /usr/lib/libgcc_s.so.1
7f2f603ef000-7f2f605ee000 ---p 00016000 08:03 2619819                    /usr/lib/libgcc_s.so.1
7f2f605ee000-7f2f605ef000 rw-p 00015000 08:03 2619819                    /usr/lib/libgcc_s.so.1
7f2f605ef000-7f2f605f0000 ---p 00000000 00:00 0 
7f2f605f0000-7f2f60e79000 rw-p 00000000 00:00 0                          [stack:10888]
7f2f60ebe000-7f2f60eda000 r--p 00000000 08:03 531575                     /usr/share/fonts/TTF/sakamoto-11.bdf
7f2f60eda000-7f2f60f49000 r-xp 00000000 08:03 2627218                    /usr/lib/libpcre.so.1.2.5
7f2f60f49000-7f2f61148000 ---p 0006f000 08:03 2627218                    /usr/lib/libpcre.so.1.2.5
7f2f61148000-7f2f61149000 r--p 0006e000 08:03 2627218                    /usr/lib/libpcre.so.1.2.5
7f2f61149000-7f2f6114a000 rw-p 0006f000 08:03 2627218                    /usr/lib/libpcre.so.1.2.5
7f2f6114a000-7f2f61173000 r-xp 00000000 08:03 2637664                    /usr/lib/libgraphite2.so.3.0.1
7f2f61173000-7f2f61373000 ---p 00029000 08:03 2637664                    /usr/lib/libgraphite2.so.3.0.1
7f2f61373000-7f2f61375000 r--p 00029000 08:03 2637664                    /usr/lib/libgraphite2.so.3.0.1
7f2f61375000-7f2f61376000 rw-p 0002b000 08:03 2637664                    /usr/lib/libgraphite2.so.3.0.1
7f2f61376000-7f2f61482000 r-xp 00000000 08:03 2627437                    /usr/lib/libglib-2.0.so.0.4400.1
7f2f61482000-7f2f61681000 ---p 0010c000 08:03 2627437                    /usr/lib/libglib-2.0.so.0.4400.1
7f2f61681000-7f2f61682000 r--p 0010b000 08:03 2627437                    /usr/lib/libglib-2.0.so.0.4400.1
7f2f61682000-7f2f61683000 rw-p 0010c000 08:03 2627437                    /usr/lib/libglib-2.0.so.0.4400.1
7f2f61683000-7f2f61684000 rw-p 00000000 00:00 0 
7f2f61684000-7f2f61689000 r-xp 00000000 08:03 2637908                    /usr/lib/libXdmcp.so.6.0.0
7f2f61689000-7f2f61888000 ---p 00005000 08:03 2637908                    /usr/lib/libXdmcp.so.6.0.0
7f2f61888000-7f2f61889000 r--p 00004000 08:03 2637908                    /usr/lib/libXdmcp.so.6.0.0
7f2f61889000-7f2f6188a000 rw-p 00005000 08:03 2637908                    /usr/lib/libXdmcp.so.6.0.0
7f2f6188a000-7f2f6188c000 r-xp 00000000 08:03 2637912                    /usr/lib/libXau.so.6.0.0
7f2f6188c000-7f2f61a8c000 ---p 00002000 08:03 2637912                    /usr/lib/libXau.so.6.0.0
7f2f61a8c000-7f2f61a8d000 r--p 00002000 08:03 2637912                    /usr/lib/libXau.so.6.0.0
7f2f61a8d000-7f2f61a8e000 rw-p 00003000 08:03 2637912                    /usr/lib/libXau.so.6.0.0
7f2f61a8e000-7f2f61ab5000 r-xp 00000000 08:03 2627185                    /usr/lib/libexpat.so.1.6.0
7f2f61ab5000-7f2f61cb4000 ---p 00027000 08:03 2627185                    /usr/lib/libexpat.so.1.6.0
7f2f61cb4000-7f2f61cb7000 r--p 00026000 08:03 2627185                    /usr/lib/libexpat.so.1.6.0
7f2f61cb7000-7f2f61cb8000 rw-p 00029000 08:03 2627185                    /usr/lib/libexpat.so.1.6.0
7f2f61cb8000-7f2f61d17000 r-xp 00000000 08:03 2637688                    /usr/lib/libharfbuzz.so.0.10000.3
7f2f61d17000-7f2f61f17000 ---p 0005f000 08:03 2637688                    /usr/lib/libharfbuzz.so.0.10000.3
7f2f61f17000-7f2f61f18000 r--p 0005f000 08:03 2637688                    /usr/lib/libharfbuzz.so.0.10000.3
7f2f61f18000-7f2f61f19000 rw-p 00060000 08:03 2637688                    /usr/lib/libharfbuzz.so.0.10000.3
7f2f61f19000-7f2f61f4d000 r-xp 00000000 08:03 2633662                    /usr/lib/libpng16.so.16.18.0
7f2f61f4d000-7f2f6214c000 ---p 00034000 08:03 2633662                    /usr/lib/libpng16.so.16.18.0
7f2f6214c000-7f2f6214d000 r--p 00033000 08:03 2633662                    /usr/lib/libpng16.so.16.18.0
7f2f6214d000-7f2f6214e000 rw-p 00034000 08:03 2633662                    /usr/lib/libpng16.so.16.18.0
7f2f6214e000-7f2f6215d000 r-xp 00000000 08:03 2622565                    /usr/lib/libbz2.so.1.0.6
7f2f6215d000-7f2f6235c000 ---p 0000f000 08:03 2622565                    /usr/lib/libbz2.so.1.0.6
7f2f6235c000-7f2f6235e000 rw-p 0000e000 08:03 2622565                    /usr/lib/libbz2.so.1.0.6
7f2f6235e000-7f2f6245b000 r-xp 00000000 08:03 2619588                    /usr/lib/libm-2.22.so
7f2f6245b000-7f2f6265a000 ---p 000fd000 08:03 2619588                    /usr/lib/libm-2.22.so
7f2f6265a000-7f2f6265b000 r--p 000fc000 08:03 2619588                    /usr/lib/libm-2.22.so
7f2f6265b000-7f2f6265c000 rw-p 000fd000 08:03 2619588                    /usr/lib/libm-2.22.so
7f2f6265c000-7f2f6266d000 r-xp 00000000 08:03 2641340                    /usr/lib/libXext.so.6.4.0
7f2f6266d000-7f2f6286c000 ---p 00011000 08:03 2641340                    /usr/lib/libXext.so.6.4.0
7f2f6286c000-7f2f6286d000 r--p 00010000 08:03 2641340                    /usr/lib/libXext.so.6.4.0
7f2f6286d000-7f2f6286e000 rw-p 00011000 08:03 2641340                    /usr/lib/libXext.so.6.4.0
7f2f6286e000-7f2f62a09000 r-xp 00000000 08:03 2619524                    /usr/lib/libc-2.22.so
7f2f62a09000-7f2f62c08000 ---p 0019b000 08:03 2619524                    /usr/lib/libc-2.22.so
7f2f62c08000-7f2f62c0c000 r--p 0019a000 08:03 2619524                    /usr/lib/libc-2.22.so
7f2f62c0c000-7f2f62c0e000 rw-p 0019e000 08:03 2619524                    /usr/lib/libc-2.22.so
7f2f62c0e000-7f2f62c12000 rw-p 00000000 00:00 0 
7f2f62c12000-7f2f62c15000 r-xp 00000000 08:03 2619587                    /usr/lib/libdl-2.22.so
7f2f62c15000-7f2f62e14000 ---p 00003000 08:03 2619587                    /usr/lib/libdl-2.22.so
7f2f62e14000-7f2f62e15000 r--p 00002000 08:03 2619587                    /usr/lib/libdl-2.22.so
7f2f62e15000-7f2f62e16000 rw-p 00003000 08:03 2619587                    /usr/lib/libdl-2.22.so
7f2f62e16000-7f2f62e2e000 r-xp 00000000 08:03 2619492                    /usr/lib/libpthread-2.22.so
7f2f62e2e000-7f2f6302d000 ---p 00018000 08:03 2619492                    /usr/lib/libpthread-2.22.so
7f2f6302d000-7f2f6302e000 r--p 00017000 08:03 2619492                    /usr/lib/libpthread-2.22.so
7f2f6302e000-7f2f6302f000 rw-p 00018000 08:03 2619492                    /usr/lib/libpthread-2.22.so
7f2f6302f000-7f2f63033000 rw-p 00000000 00:00 0 
7f2f63033000-7f2f6303e000 r-xp 00000000 08:03 2648257                    /usr/lib/libxcb-ewmh.so.2.0.0
7f2f6303e000-7f2f6323e000 ---p 0000b000 08:03 2648257                    /usr/lib/libxcb-ewmh.so.2.0.0
7f2f6323e000-7f2f6323f000 r--p 0000b000 08:03 2648257                    /usr/lib/libxcb-ewmh.so.2.0.0
7f2f6323f000-7f2f63240000 rw-p 0000c000 08:03 2648257                    /usr/lib/libxcb-ewmh.so.2.0.0
7f2f63240000-7f2f63244000 r-xp 00000000 08:03 2648254                    /usr/lib/libxcb-icccm.so.4.0.0
7f2f63244000-7f2f63443000 ---p 00004000 08:03 2648254                    /usr/lib/libxcb-icccm.so.4.0.0
7f2f63443000-7f2f63444000 r--p 00003000 08:03 2648254                    /usr/lib/libxcb-icccm.so.4.0.0
7f2f63444000-7f2f63445000 rw-p 00004000 08:03 2648254                    /usr/lib/libxcb-icccm.so.4.0.0
7f2f63445000-7f2f63466000 r-xp 00000000 08:03 2640198                    /usr/lib/libxcb.so.1.1.0
7f2f63466000-7f2f63666000 ---p 00021000 08:03 2640198                    /usr/lib/libxcb.so.1.1.0
7f2f63666000-7f2f63667000 r--p 00021000 08:03 2640198                    /usr/lib/libxcb.so.1.1.0
7f2f63667000-7f2f63668000 rw-p 00022000 08:03 2640198                    /usr/lib/libxcb.so.1.1.0
7f2f63668000-7f2f636a6000 r-xp 00000000 08:03 2649167                    /usr/lib/libfontconfig.so.1.9.0
7f2f636a6000-7f2f638a5000 ---p 0003e000 08:03 2649167                    /usr/lib/libfontconfig.so.1.9.0
7f2f638a5000-7f2f638a7000 r--p 0003d000 08:03 2649167                    /usr/lib/libfontconfig.so.1.9.0
7f2f638a7000-7f2f638ac000 rw-p 0003f000 08:03 2649167                    /usr/lib/libfontconfig.so.1.9.0
7f2f638ac000-7f2f638c1000 r-xp 00000000 08:03 2622569                    /usr/lib/libz.so.1.2.8
7f2f638c1000-7f2f63ac0000 ---p 00015000 08:03 2622569                    /usr/lib/libz.so.1.2.8
7f2f63ac0000-7f2f63ac1000 r--p 00014000 08:03 2622569                    /usr/lib/libz.so.1.2.8
7f2f63ac1000-7f2f63ac2000 rw-p 00015000 08:03 2622569                    /usr/lib/libz.so.1.2.8
7f2f63ac2000-7f2f63b7f000 r-xp 00000000 08:03 2637699                    /usr/lib/libfreetype.so.6.12.0
7f2f63b7f000-7f2f63d7e000 ---p 000bd000 08:03 2637699                    /usr/lib/libfreetype.so.6.12.0
7f2f63d7e000-7f2f63d84000 r--p 000bc000 08:03 2637699                    /usr/lib/libfreetype.so.6.12.0
7f2f63d84000-7f2f63d88000 rw-p 000c2000 08:03 2637699                    /usr/lib/libfreetype.so.6.12.0
7f2f63d88000-7f2f63d91000 r-xp 00000000 08:03 2641108                    /usr/lib/libXrender.so.1.3.0
7f2f63d91000-7f2f63f90000 ---p 00009000 08:03 2641108                    /usr/lib/libXrender.so.1.3.0
7f2f63f90000-7f2f63f91000 r--p 00008000 08:03 2641108                    /usr/lib/libXrender.so.1.3.0
7f2f63f91000-7f2f63f92000 rw-p 00009000 08:03 2641108                    /usr/lib/libXrender.so.1.3.0
7f2f63f92000-7f2f63fa7000 r-xp 00000000 08:03 2641112                    /usr/lib/libXft.so.2.3.2
7f2f63fa7000-7f2f641a6000 ---p 00015000 08:03 2641112                    /usr/lib/libXft.so.2.3.2
7f2f641a6000-7f2f641a7000 r--p 00014000 08:03 2641112                    /usr/lib/libXft.so.2.3.2
7f2f641a7000-7f2f641a8000 rw-p 00015000 08:03 2641112                    /usr/lib/libXft.so.2.3.2
7f2f641a8000-7f2f641aa000 r-xp 00000000 08:03 2642578                    /usr/lib/libXinerama.so.1.0.0
7f2f641aa000-7f2f643a9000 ---p 00002000 08:03 2642578                    /usr/lib/libXinerama.so.1.0.0
7f2f643a9000-7f2f643aa000 r--p 00001000 08:03 2642578                    /usr/lib/libXinerama.so.1.0.0
7f2f643aa000-7f2f643ab000 rw-p 00002000 08:03 2642578                    /usr/lib/libXinerama.so.1.0.0
7f2f643ab000-7f2f644e6000 r-xp 00000000 08:03 2640283                    /usr/lib/libX11.so.6.3.0
7f2f644e6000-7f2f646e5000 ---p 0013b000 08:03 2640283                    /usr/lib/libX11.so.6.3.0
7f2f646e5000-7f2f646e7000 r--p 0013a000 08:03 2640283                    /usr/lib/libX11.so.6.3.0
7f2f646e7000-7f2f646ec000 rw-p 0013c000 08:03 2640283                    /usr/lib/libX11.so.6.3.0
7f2f646ec000-7f2f646ed000 rw-p 00000000 00:00 0 
7f2f646ed000-7f2f6470f000 r-xp 00000000 08:03 2619520                    /usr/lib/ld-2.22.so
7f2f64726000-7f2f6472b000 r--s 00000000 08:03 140412                     /var/cache/fontconfig/6d78b720ace5d3bb3fea22ee600d50bf-le64.cache-7
7f2f6472b000-7f2f64730000 r--s 00000000 08:03 140411                     /var/cache/fontconfig/35045e7431f4b007379fc5bbc2da2f51-le64.cache-7
7f2f64730000-7f2f64732000 r--s 00000000 08:03 140410                     /var/cache/fontconfig/79449df53fb50ba122ae4c4c10c5c8e5-le64.cache-7
7f2f64732000-7f2f64734000 r--s 00000000 08:03 140409                     /var/cache/fontconfig/9bcaad8275e5d043434024ef82709c69-le64.cache-7
7f2f64734000-7f2f6474e000 r--s 00000000 08:03 140415                     /var/cache/fontconfig/8d4af663993b81a124ee82e610bb31f9-le64.cache-7
7f2f6474e000-7f2f648dc000 r--p 00000000 08:03 2637750                    /usr/lib/locale/locale-archive
7f2f648dc000-7f2f648ea000 rw-p 00000000 00:00 0 
7f2f648ea000-7f2f648ee000 r--s 00000000 08:03 140408                     /var/cache/fontconfig/15307eb168539589f690be8d29ed1550-le64.cache-7
7f2f648ee000-7f2f648f9000 r--s 00000000 08:03 140407                     /var/cache/fontconfig/81afcec12fadd71c4e03e0a437247ada-le64.cache-7
7f2f648f9000-7f2f64903000 r--s 00000000 08:03 141003                     /var/cache/fontconfig/d62e99ef547d1d24cdb1bd22ec1a2976-le64.cache-7
7f2f64903000-7f2f64904000 r--s 00000000 08:03 787083                     /home/self/.cache/fontconfig/f6b893a7224233d96cb72fd88691c0b4-le64.cache-7
7f2f64904000-7f2f6490d000 r--s 00000000 08:03 140401                     /var/cache/fontconfig/f349e9996a5320f6dd491cedd2b1f964-le64.cache-7
7f2f6490d000-7f2f6490e000 rw-p 00000000 00:00 0 
7f2f6490e000-7f2f6490f000 r--p 00021000 08:03 2619520                    /usr/lib/ld-2.22.so
7f2f6490f000-7f2f64910000 rw-p 00022000 08:03 2619520                    /usr/lib/ld-2.22.so
7f2f64910000-7f2f64911000 rw-p 00000000 00:00 0 
7ffd092d2000-7ffd092f3000 rw-p 00000000 00:00 0                          [stack]
7ffd0935a000-7ffd0935c000 r--p 00000000 00:00 0                          [vvar]
7ffd0935c000-7ffd0935e000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
zsh: abort (core dumped)  tint3

**Comment by tmathmeyer** [comment]
That issue should be fixed in the github version, however some weird stuff is going on with the aur version and I'm still working that out.

**Comment by tmathmeyer** [comment]
ok, AUR package fixed, you might have to force update, but it should work again!
