### ISSUE TITLE
Use a command/file as input

### ISSUE THREAD

**Issue by Fnux** [tmathmeyer/tint3#22]
Hi ! Is there a way to use a shell command, a text file or whatever as a source (id text) ?

**Comment by tmathmeyer** [comment]
Currently no. Thats a pretty good idea, I'll see if I can implement it quickly. Do you have any examples of how you think it should work?

**Comment by Fnux** [comment]
I think you should keep the actual system and just allow a command/script instead of text only :
Actually, we have :
```
[stuff]
  id text
  source *textextext*
```

Add something like this would be great :

```
[stuff]
  id command # or anything else
  source mycommand 
```

I just switched from gnome to bspwm + tint3. Glad to help you.

**Comment by Fnux** [comment]
This feature allows everyone to create their own scripts/sources. It's great.

**Comment by tmathmeyer** [comment]
the new id is "shell" and the source description will be the executed command, like
````
[stuff]
  id shell
  source echo "TEST"
````

**Comment by tmathmeyer** [comment]
Documentation will be out soon.
