### ISSUE TITLE
Battery Status Params

### ISSUE THREAD

**Issue by Fnux** [tmathmeyer/tint3#23]
Hi !

My battery status switch from green to red at 80%. Is there a way to lower the switch to something like 30/40% ?

**Comment by tmathmeyer** [comment]
Its part of a change set to the system resources management stuff, so you should see it out pretty soon. The current implementation has cutoffs at 80% and 20%.
if you want your battery to be (green: 100%-80%), (yellow 80%-20%), and (red: 20%-0%),
then in your battery config block, put:
````
[battery]
id scale
source battery BAT1
high_font #00FF00
med_font #FFFF00.
low_font #FF0000
````
Personally, I like making the background red below 20%, but thats personal preference. see the configuration.md file for how this works.

I'll leave this open until the new updates are ready and pushed.

**Comment by tmathmeyer** [comment]
fixed!
check configuration.md for more details,
but all items with "id scale" support two new options
````
cutoff:high [num]
cutoff:low [num]
````
they set the bounds accordingly.
