### ISSUE TITLE
Multi-screen

### ISSUE THREAD

**Issue by Fnux** [tmathmeyer/tint3#25]
Is there any way to manage multiple screens ? Select the screen and/or the width of the bar ?

Thanks.

**Comment by tmathmeyer** [comment]
I'm sure its possible, as plenty of other status bars do it. Currently I haven't implemented that sort of behavior, as nobody had ever requested it before (I stretch it across all threw of my monitors on my desktop). Since you're interested in it being a feature I'll start looking into it.

**Comment by Fnux** [comment]
It would be awesome ! Thank you.

**Comment by Fnux** [comment]
This [pull request](https://github.com/tmathmeyer/tint3/pull/29) is a first step. It would be nice to be able to detect each screen separetly, too.

**Comment by tmathmeyer** [comment]
are there any other changes you'd like to see for this, or should I consider the issue fixed?

**Comment by Fnux** [comment]
Can't we use xinerama in order to select the screen ? (ex: set tint3 on DP2, HDMI1 or whatever instead of the "whole screen")

**Comment by tmathmeyer** [comment]
its only been more than a year, but 06528c1bfcbdabcae47d3e56c666aba208c1554f finally solves that.
use the monitor [monitor-id], where monitor-id comes from xrandr
