### ISSUE TITLE
add font size

### ISSUE THREAD

**Issue by dotpyfe** [tmathmeyer/tint3#26]
would it be possible to add a font size option to the config file?

**Comment by tmathmeyer** [comment]
working on it!

**Comment by tmathmeyer** [comment]
this is actually a much harder problem than I thought, and with my busy schedule, it might be a while

**Comment by dotpyfe** [comment]
gotcha, thanks for the update.

**Comment by tmathmeyer** [comment]
forgot to close this issue. docs are in now. this is an example:
fontname Fantasque Sans Mono:size=30
