### ISSUE TITLE
Desktops, new config ?

### ISSUE THREAD

**Issue by Fnux** [tmathmeyer/tint3#27]
I just saw this in [the config file](https://github.com/tmathmeyer/tint3/blob/master/tint3rc) : 
```
[desktops]
  id radio
  source workspaces
  format %N %U
```
It does not work for me, but I'm able to use the following : 
```
[desktops]
  id workspace
  format %J %U
  current HIGHLIGHT|UNDERLINE # does not work ?
```

I don't understand, can you explain it to me ?

**Comment by tmathmeyer** [comment]
sorry, that config was out of date. I've put a new one there. the file "configuration.md" is a better bet for up to date flags and options.
