### ISSUE TITLE
Difference between the sample tint3rc and configuration.md

### ISSUE THREAD

**Issue by Fnux** [tmathmeyer/tint3#31]
In *tint3rc* :

```
[download]
  id network
  style graph
  source wlp3s0 down
  forground #ff0000
```

However, in *configuration.md*, it looks like we should have something like `id graph` and `source network wlp3s0 down`. Can you clarify this point ? 

Thank you !

**Comment by tmathmeyer** [comment]
shit... haha i'll fix that asap. sleep now though

**Comment by tmathmeyer** [comment]
cleaned that up a while ago
