### ISSUE TITLE
Occasional segfault with weather module

### ISSUE THREAD

**Issue by tuftedocelot** [tmathmeyer/tint3#32]
I'll get sporadic segfaults from what appears to be the weather module. It usually happens almost immediately after starting, but occasionally it'll be after a period of hours. Output from gdb:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff34c2700 (LWP 23995)]
0x000000000040a074 in weather_conditions (place=0, string=0x7fffe8000970 "") at weather.c:139
139	    container * first = _(w_weather, 0);
```

**Comment by tmathmeyer** [comment]
interesting, are you often disconnected from the internet? Also could you by any chance tell me the location you're using for weather?

**Comment by tuftedocelot** [comment]
I'm always connected to the internet; tint3 is running on my desktop. For what it's worth, I have tint3 in my xinitrc

I'll email you the location I'm using.

**Comment by tmathmeyer** [comment]
I'm sick as shit right now, but hopefully i'll get a fix soon

**Comment by tmathmeyer** [comment]
ok so im pretty sure I fixed it. I think the problem was that open weather map sometimes doesn't send a forecast string for certain areas. You could try to run it without the %W specifier, and see if it still crashes. Alternatively, run this new version and see if you get a "no forecast" message.
