### ISSUE TITLE
crash on start when using clock format %c

### ISSUE THREAD

**Issue by thugcee** [tmathmeyer/tint3#37]
To reproduce:

clone repo, compile, change example config from:
```
[time]
  id clock
  timeout 5
  format %T
shell bg.sh
```
to:
```
[time]
  id clock
  timeout 5
  format %c
```

and start tint3 with this config to get 
_Segmentation fault_
OR
_*** Error in `./tint3': munmap_chunk(): invalid pointer: 0x0000000001db8d90 ***_,
OR
double mem free error

Locale is pl_PL.utf8. With LC_ALL=C it starts, but there is some text corruption in clock.

**Comment by tmathmeyer** [comment]
fixed in the latest commit. thanks for finding this!
